### PR TITLE
Make the click-a11y script callable

### LINKED ISSUE #856: Make click-a11y script callable by external script.
# Problem

As discovered in https://github.com/uiowa/uiowa/issues/6138, the click-a11y script we use for cards and banners is not written in a way that allows it to be called by another script. It is loaded and runs automatically right away. This doesn't work for AJAX though because the script never re-runs after it has first been loaded. To work with AJAX, the script should be callable so it can be triggered to run on AJAX responses as well.

# Proposed solution

Refactor the click-a11y script to allow it to be called by another script.

### PR DESCRIPTION
**Pull request by pyrello**
Resolves #856.

Also, as part of this work, the headline component was updated to not include properties related to the content containing a link or not. Since the inclusion of the link doesn't have any affect on how the headline gets styled, we can just let the headline component be a wrapper around whatever text or link gets inserted into and avoid having the extra logic related to applying properties based on the link.

# To test

Using https://uids.brand.uiowa.edu/branches/callable_click_a11y/ to test:
- Check card examples against https://uids.brand.uiowa.edu/latest/ to see if there are any regressions.
- Confirm that unlinked card is not linked: https://uids.brand.uiowa.edu/branches/callable_click_a11y/?path=/story/components-card--with-no-link

### CODE REVIEW

File: src/components/card/Card.vue [hunk 1]
```diff
@@ -185,23 +197,35 @@ const detailsElement = computed(() => {
...
+          name="media"
+          v-else
+        ></slot>
       </div>
     </div>
 
     <div class="card__body">
       <header v-if="$slots.title">
-        <uids-headline :url="headlineLink" :text_style="headline_style">
+        <uids-headline :text_style="headline_style" class='test'>
```
Comment (joewhitsitt) [inline src/components/card/Card.vue]: is this still needed? `class='test'`

Comment (pyrello) [reply src/components/card/Card.vue]:
```suggestion
        <uids-headline :text_style="headline_style">
```

**Comment by pyrello** [comment]
Updated summary to reflect the changes to the headline component. Shouldn't affect testing instructions, since the headline is included in the card and will get tested as part of testing the cards.

**Review by joewhitsitt — APPROVED** [review]
From the testing instructions, this seems fine.
